// src/features/subscriptions/redux/subscriptionConstants.js
export const FETCH_SUBSCRIPTION_KEYS_REQUEST = 'FETCH_SUBSCRIPTION_KEYS_REQUEST';
export const FETCH_SUBSCRIPTION_KEYS_SUCCESS = 'FETCH_SUBSCRIPTION_KEYS_SUCCESS';
export const FETCH_SUBSCRIPTION_KEYS_FAILURE = 'FETCH_SUBSCRIPTION_KEYS_FAILURE';

export const GENERATE_SUBSCRIPTION_KEY_REQUEST = 'GENERATE_SUBSCRIPTION_KEY_REQUEST';
export const GENERATE_SUBSCRIPTION_KEY_SUCCESS = 'GENERATE_SUBSCRIPTION_KEY_SUCCESS';
export const GENERATE_SUBSCRIPTION_KEY_FAILURE = 'GENERATE_SUBSCRIPTION_KEY_FAILURE';

export const DEACTIVATE_SUBSCRIPTION_KEY_REQUEST = 'DEACTIVATE_SUBSCRIPTION_KEY_REQUEST';
export const DEACTIVATE_SUBSCRIPTION_KEY_SUCCESS = 'DEACTIVATE_SUBSCRIPTION_KEY_SUCCESS';
export const DEACTIVATE_SUBSCRIPTION_KEY_FAILURE = 'DEACTIVATE_SUBSCRIPTION_KEY_FAILURE';