// src/features/devices/redux/deviceConstants.js
export const FETCH_DEVICES_REQUEST = "FETCH_DEVICES_REQUEST";
export const FETCH_DEVICES_SUCCESS = "FETCH_DEVICES_SUCCESS";
export const FETCH_DEVICES_FAILURE = "FETCH_DEVICES_FAILURE";

export const FETCH_DEVICE_BY_ID_REQUEST = "FETCH_DEVICE_BY_ID_REQUEST";
export const FETCH_DEVICE_BY_ID_SUCCESS = "FETCH_DEVICE_BY_ID_SUCCESS";
export const FETCH_DEVICE_BY_ID_FAILURE = "FETCH_DEVICE_BY_ID_FAILURE";

export const CREATE_DEVICE_REQUEST = "CREATE_DEVICE_REQUEST";
export const CREATE_DEVICE_SUCCESS = "CREATE_DEVICE_SUCCESS";
export const CREATE_DEVICE_FAILURE = "CREATE_DEVICE_FAILURE";

export const UPDATE_DEVICE_REQUEST = "UPDATE_DEVICE_REQUEST";
export const UPDATE_DEVICE_SUCCESS = "UPDATE_DEVICE_SUCCESS";
export const UPDATE_DEVICE_FAILURE = "UPDATE_DEVICE_FAILURE";

export const DELETE_DEVICE_REQUEST = "DELETE_DEVICE_REQUEST";
export const DELETE_DEVICE_SUCCESS = "DELETE_DEVICE_SUCCESS";
export const DELETE_DEVICE_FAILURE = "DELETE_DEVICE_FAILURE";

// Removed VIP specific constants
// export const UPDATE_DEVICE_STATUS_REQUEST = 'UPDATE_DEVICE_STATUS_REQUEST';
// export const UPDATE_DEVICE_STATUS_SUCCESS = 'UPDATE_DEVICE_STATUS_SUCCESS';
// export const UPDATE_DEVICE_STATUS_FAILURE = 'UPDATE_DEVICE_STATUS_FAILURE';
